version: '3.8'

services:
  mongodb:
    image: 'mongo'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: admin
    ports:
      - "27017:27017"
    volumes:
      - /tmp/data:/data/db
    networks:
      - shared-net

  backend:
    image: batool83/backend:latest
    ports:
      - "8080:8080"
      - "8085:8085"
    restart: always
    depends_on:
      - mongodb
    networks:
      - shared-net

  frontend:
    image: batool83/frontend:latest
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - mongodb
    networks:
      - shared-net

networks:
  shared-net:
    driver: bridge