version: '3'

services:
  mongodb:
    image: 'mongo'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: admin
    ports:
      - 27017:27017
    container_name: mongodb
    volumes:
      - /tmp/data:/data/db
    networks:
      - shared-net
  # app:
  #   image: backend
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #     - "8085:8085"
  #   restart: always
  #   links:
  #     - mongodb
  #   depends_on:
  #     - mongodb
  #   networks:
  #     - shared-net
networks:
  shared-net:
    driver: bridge