name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: batool-win
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Get Git Commit SHA and Message
        id: git-info
        run: |
          echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      
      # Maven Build Backend JAR
      - name: Maven Build Backend JAR
        run: |
          cd backend && mvn clean install -DskipTests

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and Push Docker Image for Backend
      - name: Build and Push Docker Image for Backend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:${{ env.COMMIT_SHA }} -f backend/Dockerfile backend
          docker tag ${{ secrets.DOCKER_USERNAME }}/backend:${{ env.COMMIT_SHA }} ${{ secrets.DOCKER_USERNAME }}/backend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/backend:${{ env.COMMIT_SHA }}
          docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest

      # Build and Push Docker Image for Frontend
      - name: Build and Push Docker Image for Frontend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:${{ env.COMMIT_SHA }} -f frontend/Dockerfile frontend
          docker tag ${{ secrets.DOCKER_USERNAME }}/frontend:${{ env.COMMIT_SHA }} ${{ secrets.DOCKER_USERNAME }}/frontend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend:${{ env.COMMIT_SHA }}
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest

  deploy:
    runs-on: batool-win
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Docker Compose
        run: |
          docker-compose -f docker-compose.yml down
          sleep 10;
          docker-compose -f docker-compose.yml up --build -d

  stop-services:
    runs-on: batool-win
    needs: deploy
    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Stop Docker Compose
        run: |
          docker-compose -f docker-compose.yml down