name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: batool-self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      # Maven Build Backend JAR
      - name: Maven Build Backend JAR
        run: |
          cd backend && mvn clean install -DskipTests
        
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and Push Docker Image for Backend
      - name: Build and Push Docker Image for Backend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:latest -f backend/Dockerfile backend
          docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest

      # Build and Push Docker Image for Frontend
      - name: Build and Push Docker Image for Frontend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest -f frontend/Dockerfile frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest

      # Run Docker Compose
      - name: Run Docker Compose
        run: |
          docker-compose -d -f docker-compose.yml up --build